### ISSUE TITLE
Publish a Python < 3.4 specific wheel on PyPI

### ISSUE THREAD

**Issue by estan** [ColinDuquesnoy/pyqt_distutils#3]
When doing `pip install` on Python < 3.4 it installs the wheel, which does not have `enum34` as a dependency. You have to specify `--no-binary pyqt_distutils` to pip for it to work.

Would be nice if a wheel that works for Python < 3.4 could be published on PyPI.

**Comment by ColinDuquesnoy** [comment]
Thank you for reporting! I'll see what I can do. (I'll probably get rid of the enum34 dependency.)

**Comment by estan** [comment]
:+1:

**Comment by ColinDuquesnoy** [comment]
Should be OK now. A new release has been upload to pypi.
