### ISSUE TITLE
0.7.2 is not installable via setup tools setup_requires 

### ISSUE THREAD

**Issue by mpasternak** [ColinDuquesnoy/pyqt_distutils#8]
Hi, 

the best place to require pyqt_distutils would be "setup_requires" with setup tools. Unfortunately, version 0.7.2 is not installable with setuptools, as it produces a traceback with Import Error. 

The good thing is, it looks like it's fixed in git.

Would you kindly release 0.7.3 ?

**Comment by ColinDuquesnoy** [comment]
What traceback do you have?

I've compared the version on pypi and the git version, they are identical. I don't see how it could be fixed in git.

**Comment by mpasternak** [comment]
I'll prepare a minimal example and probably an additional test for the main branch thanks

Wysłane z iPhone'a

Dnia 13.05.2017 o godz. 11:58 Colin Duquesnoy <notifications@github.com> napisał(a):

**Comment by mpasternak** [comment]
Hey, 

thanks for a quick reply, 

I'm no longer getting any traceback and the version from setup_requires gets downloaded. It is not being installed though, but I doubt this has anything to do with pyqt_distutils itself. I'm closing this issue, thanks. 

I planned to use setup_requires setting but it is somehow cumbersome. I find it way easier to just put things into requirements_dev.txt and install it by hand, before running setup. 

What's your experience, would you suggest this approach as the proper one?

**Comment by ColinDuquesnoy** [comment]
@mpasternak AFAIK setup_requires is bad since it internally relies on distutils/easy-install (If I am correct, distutils is deprecated).

For development packages such as pyqt-distutils, I usually use requirements_dev.txt
